### ISSUE TITLE
1.1.0 seems to be broken

### ISSUE THREAD

**Issue by michalbundyra** [http-interop/http-server-handler#12]
Please see these tests:
https://travis-ci.org/zendframework/zend-stratigility/jobs/332049603#L644

So the problem is only on the latest release. It's because the interface extends PSR-15 interface and method defined in the PSR-15 interface typehint against PST-15 interface, not as before interop interface. Basically 1.1.0 has a BC Break...

**Comment by shadowhand** [comment]
Okay, so we need to untag 1.1 and make it 2.0?

**Comment by michalbundyra** [comment]
I've just noted that I've opened issue in the wrong repository. `http-server-handler` is fine, the problem is only with `http-server-middleware` 1.1.0.
