### ISSUE TITLE
"replace" http-interop/http-middleware in composer?

### ISSUE THREAD

**Issue by michalbundyra** [http-interop/http-server-handler#3]
Should we have:
```json
"replace": {
    "http-interop/http-middleware": "0.*"
}
```

in `composer.json`?

https://getcomposer.org/doc/04-schema.md#replace

**Comment by shadowhand** [comment]
I think that would make sense. @http-interop/http-request-handlers anyone else?

**Comment by oscarotero** [comment]
Good for me too.

**Comment by weierophinney** [comment]
The problem with having `replace` in there is that it doesn't allow us to install them side-by-side. That means that if a developer adds this package to their repo, it will remove a previous http-middleware installation... and their existing code is now broken.

If we do not include this, then somebody can provide a shim that adapts existing code to the new interfaces, allowing them to live side-by-side while the developer iteratively updates their code to the new interfaces.

**Comment by michalbundyra** [comment]
@weierophinney
Please note that both libraries have exactly the same namespaces and interfaces names. I think then it will be not possible use both side-by-side and we need either "conflict" or "replace".

**Comment by weierophinney** [comment]
@webimpress I missed that aspect; I was assuming this package had different namespace(s).

In that case, however, the conflict only occurs starting with 0.5, does it not? As such, I'd recommend ">=0.5.0" instead.
