### ISSUE TITLE
Should we add conflict with http-interop/http-middleware 0.5?

### ISSUE THREAD

**Issue by michalbundyra** [http-interop/http-server-handler#7]
This package has the same namespace and contains exactly the same class, both packages can't be used together.

**Comment by shadowhand** [comment]
https://github.com/http-interop/http-server-handler/tree/master/src
https://github.com/http-interop/http-server-middleware/tree/master/src

Two different classes. Same namespace for two different packages is okay, afaik?

**Comment by shadowhand** [comment]
See also composer/composer#4605

**Comment by shadowhand** [comment]
Doh, I misread the title of this completely. I think we need a `conflict` here, right @weierophinney ?

**Comment by weierophinney** [comment]
Yes, or a replace.

**Comment by michalbundyra** [comment]
@weierophinney @shadowhand 
> Yes, or a replace.

Cannot be `replace` because this library contains just ONE interface, not both. Must be `conflict` IMHO
